#!/bin/bash
echo $(pwd)
docker container run \
-it \
--rm \
--name=spiking-model-monitor \
-v "$(pwd)":/app \
-v "$(pwd)"/../spiking-model-configuration/configuration/:/app/src/configfiles \
-v "$(pwd)"/../spiking-model-configuration/src/:/app/src/configuration \
-p 8082:3000 \
louisross/spiking-model-monitor:1.0 \
bash
